### ISSUE TITLE
Netplan module delete ip address section when a route is added

### ISSUE THREAD

**Issue by carmine73** [lets00/ansible#2]
##### SUMMARY
Netplan module delete ip address section when a route is added

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netplan

##### ANSIBLE VERSION
```
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/carmine/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT
```
target OS version: Ubuntu 18.04 LTS
ansible OS version: Ubuntu 19.04
```
##### STEPS TO REPRODUCE
```
  vars:
    my_net: 10.0.0.0/8
    my_gw: 192.168.56.1

  tasks:
  - name: add a netplan permanent route
    netplan:
      filename: 01-netcfg-test
      interface-id: enp0s8
      type: ethernets
      state: present
      routes:
       - { to: '{{ my_net }}', via: '{{ my_gw }}' }
```

##### EXPECTED RESULTS
The route is added in yaml file, as in following example:
```
    enp0s8:
      dhcp4: no
      addresses: [192.168.56.16/24]
      routes:
      - to: 10.0.0.0/8
        via: 192.168.56.1
```

##### ACTUAL RESULTS
The route is added but ip address section has been deleted:
```
    enp0s8:
      routes:
      - to: 10.0.0.0/8
        via: 192.168.56.1
```
look at the diffs before and after:
```
$ diff -u 01-netcfg-test.before.yaml 01-netcfg-test.after.yaml 
--- 01-netcfg-test.before.yaml	2019-08-08 08:13:15.668000000 +0000
+++ 01-netcfg-test.after.yaml	2019-08-08 08:18:58.068000000 +0000
@@ -1,18 +1,20 @@
-# This file describes the network interfaces available on your system
-# For more information, see netplan(5).
 network:
-  version: 2
-  renderer: networkd
   ethernets:
     enp0s3:
-      dhcp4: no
-      addresses: [192.168.10.16/24, "fd00::16/64"]
+      addresses:
+      - 192.168.10.16/24
+      - fd00::16/64
+      dhcp4: false
       gateway4: 192.168.10.1
       nameservers:
-        search: [mydomain.it, mydomain.local]
-        # 127.0.0.1 is the local dnsmasq dns server
-        addresses: [127.0.0.1]
-        #addresses: [8.8.8.8, 8.8.4.4]
+        addresses:
+        - 127.0.0.1
+        search:
+        - mydomain.it
+        - mydomain.local
     enp0s8:
-      dhcp4: no
-      addresses: [192.168.56.16/24]
+      routes:
+      - to: 10.0.0.0/8
+        via: 192.168.56.1
+  renderer: networkd
+  version: 2
```

##### MORE COMMENTS
- cosmetic: renderer and version are moved to the end of the file
- docs: you should add that yaml extension must not be used in filename parameter (examples are correct)
```
options:
  filename:
    description:
      - Name of file without yaml extension that will be create or open to add/remove network
        interfaces.
    required: true

```

**Comment by lets00** [comment]
Thank you @carmineesposito73 for your comment. You're right. The module is deleting parameters already in the file that were not declared in the module. I fix this, please test again to verify if now it works.

About cosmetic comments, in my generated files, renderer and version are in the end of the file:
E.g
```
network:
  ethernets:
    eth1:
      addresses:
      - 192.168.1.100/24
      routes:
      - metric: 0
        scope: global
        table: 1
        to: 100.100.100.100/0
        type: unicast
        via: 11.11.11.11/8
      - to: 100.100.100.100/0
        via: 0.0.0.0/8
      - to: 100.100.100.100/0
        via: 0.0.0.1/8
      - to: 100.100.100.100/0
        via: 0.0.0.2/8
      - to: 1.1.1.1/0
        via: 0.0.0.3/8
      - to: 100.100.100.100/0
        via: 0.0.0.10/8
  renderer: networkd
  version: 2
```
About the filename parameter, I will change the code to to allow the user to define the extension. Some people prefer to use the .yml extension (others .yaml). I will improve that.
