### ISSUE TITLE
Netplan module nameserver configuration is wrong

### ISSUE THREAD

**Issue by carmine73** [lets00/ansible#3]
##### SUMMARY
Netplan module nameserver configuration is wrong

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netplan

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/carmine/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Jul  9 2019, 16:43:02) [GCC 8.3.0]

```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT
```
target OS version: Ubuntu 18.04 LTS
ansible OS version: Ubuntu 19.04
```
##### STEPS TO REPRODUCE
```
  vars:
    my_dns_server_1: 1.1.1.1
    my_dns_search_1: netplan.test.net

  tasks:
  - name: set dns nameservers
    netplan:
      filename: 01-netcfg-test
      interface_id: enp0s8
      type: ethernets
      state: present
      nameservers_addresses:
       - "{{ my_dns_server_1 }}"

  - name: set dns search
    netplan:
      filename: 01-netcfg-test
      interface_id: enp0s8
      type: ethernets
      state: present
      nameservers_search:
       - "{{ my_dns_search_1 }}"
```

##### EXPECTED RESULTS
The route is added in yaml file, as in following example:
```
    enp0s8:
      addresses:
      - 192.168.56.16/24
      dhcp4: false
      nameservers:
        addresses:
        - 1.1.1.1
        search:
        - netplan.test.net
```

##### ACTUAL RESULTS
nameservers added but the fields are wrong:
```
    enp0s8:
      addresses:
      - 192.168.56.16/24
      dhcp4: false
      nameservers-addresses:
      - 1.1.1.1
      nameservers-search:
      - netplan.test.net
```
